module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('cards', [
    {
      name: 'Ace of Hearts',
      value: '1',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Two of Hearts',
      value: '2',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Three of Hearts',
      value: '3',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Four of Hearts',
      value: '4',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Five of Hearts',
      value: '5',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Six of Hearts',
      value: '6',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Seven of Hearts',
      value: '7',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Eight of Hearts',
      value: '8',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Nine of Hearts',
      value: '9',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ten of Hearts',
      value: '10',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Jake of Hearts',
      value: 'J',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Queen of Hearts',
      value: 'Q',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'King of Hearts',
      value: 'K',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ace of Clubs',
      value: '1',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Two of Clubs',
      value: '2',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Three of Clubs',
      value: '3',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Four of Clubs',
      value: '4',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Five of Clubs',
      value: '5',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Six of Clubs',
      value: '6',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Seven of Clubs',
      value: '7',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Eight of Clubs',
      value: '8',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Nine of Clubs',
      value: '9',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ten of Clubs',
      value: '10',
      suit: 'hearts',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Jake of Clubs',
      value: 'J',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Queen of Clubs',
      value: 'Q',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'King of Clubs',
      value: 'K',
      suit: 'clubs',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ace of Diamonds',
      value: '1',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Two of Diamonds',
      value: '2',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Three of Diamonds',
      value: '3',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Four of Diamonds',
      value: '4',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Five of Diamonds',
      value: '5',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Six of Diamonds',
      value: '6',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Seven of Diamonds',
      value: '7',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Eight of Diamonds',
      value: '8',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Nine of Diamonds',
      value: '9',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ten of Diamonds',
      value: '10',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Jake of Diamonds',
      value: 'J',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Queen of Diamonds',
      value: 'Q',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'King of Diamonds',
      value: 'K',
      suit: 'diamonds',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ace of Spades',
      value: '1',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Two of Spades',
      value: '2',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Three of Spades',
      value: '3',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Four of Spades',
      value: '4',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Five of Spades',
      value: '5',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Six of Spades',
      value: '6',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Seven of Spades',
      value: '7',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Eight of Spades',
      value: '8',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Nine of Spades',
      value: '9',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ten of Spades',
      value: '10',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Jake of Spades',
      value: 'J',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Queen of Spades',
      value: 'Q',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'King of Spades',
      value: 'K',
      suit: 'spades',
      isJoker: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ], {}),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('cards', null, {}),
};
